title: PMLR Volume 1
description: > # this means to ignore newlines until "baseurl:"
  PMLR Volume 1: Gaussian Processes in Practice.
baseurl: "/v1"
url: "http://proceedings.mlr.press"
twitter_username: mlresearch
github_username:  mlresearch

# Build settings
markdown: kramdown
theme: minima
