---
booktitle: Gaussian Processes in Practice
series: Proceedings of Machine Learning Research
volume: 1
start: 2006-06-12
end: 2006-06-13
published: 2007-03-11
comments: false
year: '2006'
shortname: GPIP
bibsource: http://jmlr.csail.mit.edu/proceedings/
layout: proceedings
id: LawrenceNSACQ2006
month: 0
abstract: ''
sections: 
editor:
- given: Neil
  family: Lawrence
- given: Anton
  family: Schwaighofer
- given: Joaquin
  family: Quiñonero Candela
title: 'PMLR Volume 1: Gaussian Processes in Practice'
email: ''
description: Gaussian Processes in Practice, Bletchley Park, UK
url: http://proceedings.mlr.press
baseurl: "/v1"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v1
conference:
  name: Gaussian Processes in Practice
  url: http://gpss.cc/gpip/
  location: Bletchley Park, UK
  dates:
  - 2006-06-12
  - 2006-06-13
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v1.bib
