# .github/workflows/deploy-binaries.yml
name: Deploy Binary Files

on:
  push:
    branches:
      - binaries

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Binaries branch
      uses: actions/checkout@v2
      with:
        ref: binaries

    - name: Setup Git for deployment
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Checkout gh-pages branch
      run: |
        git fetch origin
        git checkout gh-pages
        git pull origin gh-pages

    - name: Deploy binary files
      run: |
        cp -r * ../ # Copy all files to a parent directory to preserve structure
        cd ../
        git add .
        git commit -m "Deploy binary files"
        git push origin gh-pages
